# Generated by Django 5.1.7 on 2025-03-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("downvotes", models.PositiveIntegerField(default=0)),
                ("date_posted", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("professor", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("num_credits", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_toughness", models.IntegerField(default=0)),
                ("teaching_quality", models.IntegerField(default=0)),
                ("workload", models.IntegerField(default=0)),
                ("exam_difficulty", models.IntegerField(default=0)),
                ("grading_strictness", models.IntegerField(default=0)),
                ("resources_provided", models.IntegerField(default=0)),
                ("recommendation", models.IntegerField(default=0)),
                ("grade_obtained", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="api.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="link", max_length=100)),
                ("remarks", models.CharField(default="", max_length=255)),
                ("url", models.URLField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("downvotes", models.PositiveIntegerField(default=0)),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="api.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "email",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("batch", models.CharField(max_length=10)),
                ("branch", models.CharField(max_length=100)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AddField(
            model_name="comment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources_shared",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="coursemetrics",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="api.student",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.student",
            ),
        ),
    ]
