# Generated by Django 5.1.7 on 2025-03-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('professor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_toughness_avg', models.FloatField()),
                ('workload_avg', models.FloatField()),
                ('recommended', models.PositiveIntegerField()),
                ('not_recommended', models.PositiveIntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='RatingDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('content_toughness', 'Content Toughness'), ('workload', 'Workload')], max_length=50)),
                ('value', models.IntegerField()),
                ('count', models.IntegerField()),
                ('course_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='api.coursemetrics')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('contributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.course')),
            ],
        ),
    ]
